### ISSUE TITLE
如何关闭主菜单大写显示

### ISSUE THREAD

**Issue by linbojin** [MOxFIVE/hexo-theme-yelee#158]
你好，问题如下：
这是我在_config.yaml 的设置

```
# Header | 主菜单
## About Page: `hexo new page about`
## Tags Cloud Page: `hexo new page tags`
menu:
  Home: /
  Archives: /archives/
  #随笔: /tags/随笔
  Tags: /tags/
  About: /about/
```

但是显示之后全部被变成大写了：
![image](https://cloud.githubusercontent.com/assets/5894707/19837978/0d0704b0-9f00-11e6-9eae-67e4afaddc2a.png)

如何才能只要首字母大写？
