### ISSUE TITLE
github会把bootCDN给墙了导致主题显示各种问题

### ISSUE THREAD

**Issue by Criya** [MOxFIVE/hexo-theme-yelee#233]
一开始也是localhost测试没问题，部署到github上就显示不了了。f12看了一下network cdn基本都挂了。
然后改了一下`_config.yml`里的CDN, 有几个css没找到别的就没改了。
```
CDN:
  jquery: //cdn.jsdelivr.net/gh/jquery/jquery@3.2.1/dist/jquery.min.js
  require: //cdnjs.cloudflare.com/ajax/libs/require.js/2.2.0/require.min.js
  fontawesome: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
  fancybox_js: //cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.5/jquery.fancybox.min.js 
  fancybox_css: //cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.css
  animate_css: //cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css
  jquery_ui_js: //cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js
  jquery_ui_css: //cdn.bootcss.com/jqueryui/1.10.4/css/jquery-ui.min.css
  pace_js: //cdnjs.cloudflare.com/ajax/libs/pace/1.0.2/pace.min.js
  clipboard: //cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.1/clipboard.min.js
  mathjax: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js 
  scrollreveal: //cdnjs.cloudflare.com/ajax/libs/scrollReveal.js/3.4.0/scrollreveal.min.js

```
因为那几个社交logo也是用的bootcdn的在我这也不行，改了一下source/css/_partial/customise/social-icon.styl
我用的是[simple-icons](https://github.com/simple-icons/simple-icons)。
```
.GitHub
        background url(//cdn.jsdelivr.net/npm/simple-icons@latest/icons/github.svg) no-repeat white
        background-size 100%
        background-position 50% 100%

```
