### ISSUE TITLE
侧边栏上面的矩形区域的颜色在哪改？

### ISSUE THREAD

**Issue by ge-ce** [MOxFIVE/hexo-theme-yelee#56]
侧边栏上面矩形区域的颜色好像是随机出现的，我想让他变成固定的。。

**Comment by zwj47** [comment]
main.js 里面有个随机颜色

**Comment by MOxFIVE** [comment]
同上，把随机颜色的 JS 代码删掉，
https://github.com/MOxFIVE/hexo-theme-yelee/blob/master/source/js/main.js#L142

然后再到 CSS 里改默认颜色
https://github.com/MOxFIVE/hexo-theme-yelee/blob/master/source/css/_partial/main.styl#L46
```css
.overlay{
    background-color: black;
    opacity: 0.7;
}
```
