### ISSUE TITLE
Multi-language support 多語言支持？

### ISSUE THREAD

**Issue by ShinoharaYuri** [MOxFIVE/hexo-theme-yelee#60]
請問可以嗎~

**Comment by MOxFIVE** [comment]
Any Contribution is Welcome!
歡迎協助完善翻譯

**Comment by ShinoharaYuri** [comment]
版權宣告還是簡體

**Comment by ShinoharaYuri** [comment]
閱讀更多也是簡體……

**Comment by MOxFIVE** [comment]
```yaml
# 简体
more: 阅读全文

# 繁體
more: 查看全文
```
繁體並不是單純地逐字翻譯簡體
