### ISSUE TITLE
Center images 图片居中

### ISSUE THREAD

**Issue by biggercoffee** [MOxFIVE/hexo-theme-yelee#87]
你好，作者，我想让图片居中有配置的吗？就和简书一样，当图片不够大的时候，默认就是居中的。

**Comment by MOxFIVE** [comment]
目前没有提供配置，要默认居中图片的话，把下面这行代码贴到对应文件末尾
```css
.article img {display: block;}
```
文件地址： `/yelee/source/css/_partial/article.styl`
Put above CSS code to the end of `article.styl`
